# Generated by Django 5.0.1 on 2024-01-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscription',
        ),
    ]
