# Generated by Django 5.0.1 on 2024-01-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='content',
        ),
    ]
