# Generated by Django 5.0.1 on 2024-01-15 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('subscription', '0002_subscription_discount_alter_subscription_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='subsription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription'),
        ),
    ]
